#ifndef LISTA_PRODUCTOS_H
#define LISTA_PRODUCTOS_H

#include <vector>
#include "producto.h"

inline std::vector<Producto> obtenerListaProductos() {
    return {
        // Electrónica (20)
        {"Smartphone Galaxy S24", "Teléfono inteligente de última generación", "Samsung", "Electrónica", "E001", "img/electronica/E001.jpg", 18000.0},
        {"iPhone 15 Pro", "Teléfono inteligente Apple", "Apple", "Electrónica", "E002", "img/electronica/E002.jpg", 25000.0},
        {"Laptop Inspiron 15", "Computadora portátil de alto rendimiento", "Dell", "Electrónica", "E003", "img/electronica/E003.jpg", 17000.0},
        {"MacBook Air M2", "Portátil ultraligero", "Apple", "Electrónica", "E004", "img/electronica/E004.jpg", 28000.0},
        {"Smart TV 55'' 4K", "Televisor inteligente 4K UHD", "LG", "Electrónica", "E005", "img/electronica/E005.jpg", 12000.0},
        {"Smart TV 65'' OLED", "Televisor OLED de alta definición", "Sony", "Electrónica", "E006", "img/electronica/E006.jpg", 35000.0},
        {"Auriculares inalámbricos WH-1000XM5", "Auriculares con cancelación de ruido", "Sony", "Electrónica", "E007", "img/electronica/E007.jpg", 6000.0},
        {"AirPods Pro 2", "Auriculares inalámbricos Apple", "Apple", "Electrónica", "E008", "img/electronica/E008.jpg", 5500.0},
        {"Tablet Galaxy Tab S8", "Tableta Android de alto rendimiento", "Samsung", "Electrónica", "E009", "img/electronica/E009.jpg", 9000.0},
        {"iPad Pro 11", "Tableta profesional Apple", "Apple", "Electrónica", "E010", "img/electronica/E010.jpg", 18000.0},
        {"Cámara Digital EOS 250D", "Cámara réflex digital", "Canon", "Electrónica", "E011", "img/electronica/E011.jpg", 14000.0},
        {"Cámara Mirrorless Alpha 7", "Cámara sin espejo profesional", "Sony", "Electrónica", "E012", "img/electronica/E012.jpg", 32000.0},
        {"Smartwatch Versa 4", "Reloj inteligente deportivo", "Fitbit", "Electrónica", "E013", "img/electronica/E013.jpg", 3500.0},
        {"Smartwatch Series 9", "Reloj inteligente Apple", "Apple", "Electrónica", "E014","img/electronica/E014.jpg", 9000.0},
        {"Bocina Bluetooth SoundLink", "Bocina portátil inalámbrica", "Bose", "Electrónica", "E015","img/electronica/E015.jpg", 2500.0},
        {"Bocina Bluetooth Flip 6", "Bocina portátil resistente al agua", "JBL", "Electrónica", "E016","img/electronica/E016.jpg", 2200.0},
        {"Monitor 27'' 2K", "Monitor de alta resolución", "Acer", "Electrónica", "E017","img/electronica/E017.jpg", 4800.0},
        {"Monitor 32'' 4K", "Monitor profesional para diseño", "Dell", "Electrónica", "E018","img/electronica/E018.jpg", 9500.0},
        {"Router WiFi 6", "Router de alta velocidad", "TP-Link", "Electrónica", "E019","img/electronica/E019.jpg", 1800.0},
        {"Disco SSD 1TB", "Almacenamiento sólido rápido", "Samsung", "Electrónica", "E020","img/electronica/E020.jpg", 2100.0},

        // Hogar y cocina (20)
        {"Cafetera Espresso", "Cafetera automática para espresso", "DeLonghi", "Hogar y cocina", "H001", "img/hogar y cocina/H001.jpg", 3500.0},
        {"Cafetera de goteo", "Cafetera programable", "Hamilton Beach", "Hogar y cocina", "H002","img/hogar y cocina/H002.jpg", 1200.0},
        {"Aspiradora sin bolsa", "Aspiradora ciclónica potente", "Philips", "Hogar y cocina", "H003","img/hogar y cocina/H003.jpg", 2500.0},
        {"Aspiradora robot", "Robot aspirador inteligente", "iRobot", "Hogar y cocina", "H004","img/hogar y cocina/H004.jpg", 7000.0},
        {"Juego de sábanas Queen", "Sábanas de algodón 400 hilos", "Casa Blanca", "Hogar y cocina", "H005","img/hogar y cocina/H005.jpg", 900.0},
        {"Juego de sábanas King", "Sábanas suaves y frescas", "Luna", "Hogar y cocina", "H006","img/hogar y cocina/H006.jpg", 1100.0},
        {"Olla de presión", "Olla de presión de acero inoxidable", "Presto", "Hogar y cocina", "H007","img/hogar y cocina/H007.jpg", 1300.0},
        {"Sartén antiadherente", "Sartén de 28cm", "T-fal", "Hogar y cocina", "H008","img/hogar y cocina/H008.jpg", 600.0},
        {"Licuadora profesional", "Licuadora de alta potencia", "Oster", "Hogar y cocina", "H009","img/hogar y cocina/H009.jpg", 1800.0},
        {"Licuadora personal", "Licuadora compacta para smoothies", "NutriBullet", "Hogar y cocina", "H010","img/hogar y cocina/H010.jpg", 950.0},
        {"Mesa auxiliar", "Mesa pequeña para sala", "Ikea", "Hogar y cocina", "H011","img/hogar y cocina/H011.jpg", 850.0},
        {"Silla plegable", "Silla ligera y resistente", "Home Collection", "Hogar y cocina", "H012","img/hogar y cocina/H012.jpg", 400.0},
        {"Microondas 20L", "Microondas compacto", "Mabe", "Hogar y cocina", "H013", "img/hogar y cocina/H013.jpg",1700.0},
        {"Refrigerador 14 pies", "Refrigerador con congelador", "Whirlpool", "Hogar y cocina", "H014","img/hogar y cocina/H014.jpg", 12000.0},
        {"Tostadora 2 rebanadas", "Tostadora eléctrica", "Black+Decker", "Hogar y cocina", "H015","img/hogar y cocina/H015.jpg", 500.0},
        {"Batidora de mano", "Batidora eléctrica", "KitchenAid", "Hogar y cocina", "H016", "img/hogar y cocina/H016.jpg",1300.0},
        {"Freidora de aire", "Freidora sin aceite", "Ninja", "Hogar y cocina", "H017","img/hogar y cocina/H017.jpg", 2500.0},
        {"Plancha de vapor", "Plancha para ropa", "Rowenta", "Hogar y cocina", "H018", "img/hogar y cocina/H018.jpg",900.0},
        {"Ventilador de torre", "Ventilador silencioso", "Honeywell", "Hogar y cocina", "H019", "img/hogar y cocina/H019.jpg",1600.0},
        {"Calefactor portátil", "Calefactor eléctrico", "Imaco", "Hogar y cocina", "H020", "img/hogar y cocina/H020.jpg",1200.0},

        // Moda y Accesorios (20)
        {"Camiseta básica", "Camiseta de algodón unisex", "H&M", "Moda y Accesorios", "M001", "img/moda y accesorios/M001.jpg", 250.0},
        {"Vaqueros slim fit", "Pantalón de mezclilla azul", "Levi's", "Moda y Accesorios", "M002", "img/moda y accesorios/M002.jpg", 1200.0},
        {"Zapatillas deportivas", "Tenis para correr", "Nike", "Moda y Accesorios", "M003", "img/moda y accesorios/M003.jpg", 1800.0},
        {"Reloj de pulsera", "Reloj analógico clásico", "Casio", "Moda y Accesorios", "M004",  "img/moda y accesorios/M004.jpg",900.0},
        {"Bolso tote", "Bolso grande de tela", "Zara", "Moda y Accesorios", "M005", "img/moda y accesorios/M005.jpg", 700.0},
        {"Gafas de sol polarizadas", "Lentes de sol UV400", "Ray-Ban", "Moda y Accesorios", "M006", "img/moda y accesorios/M006.jpg", 1500.0},
        {"Sudadera con capucha", "Sudadera cómoda", "Adidas", "Moda y Accesorios", "M007", "img/moda y accesorios/M007.jpg", 950.0},
        {"Pantalón deportivo", "Pantalón para ejercicio", "Puma", "Moda y Accesorios", "M008", "img/moda y accesorios/M008.jpg", 800.0},
        {"Chaqueta impermeable", "Chaqueta ligera para lluvia", "Columbia", "Moda y Accesorios", "M009", "img/moda y accesorios/M009.jpg", 1600.0},
        {"Vestido casual", "Vestido de verano", "Bershka", "Moda y Accesorios", "M010", "img/moda y accesorios/M010.jpg", 1100.0},
        {"Sandalias planas", "Sandalias cómodas", "C&A", "Moda y Accesorios", "M011", "img/moda y accesorios/M011.jpg", 400.0},
        {"Botines de piel", "Botines para dama", "Flexi", "Moda y Accesorios", "M012", "img/moda y accesorios/M012.jpg", 1700.0},
        {"Cinturón de cuero", "Cinturón clásico", "Dockers", "Moda y Accesorios", "M013", "img/moda y accesorios/M013.jpg", 350.0},
        {"Corbata de seda", "Corbata elegante", "Massimo Dutti", "Moda y Accesorios", "M014",  "img/moda y accesorios/M014.jpg",600.0},
        {"Blusa manga larga", "Blusa formal", "Mango", "Moda y Accesorios", "M015", "img/moda y accesorios/M015.jpg", 800.0},
        {"Falda plisada", "Falda elegante", "Pull&Bear", "Moda y Accesorios", "M016", "img/moda y accesorios/M016.jpg", 900.0},
        {"Calcetines deportivos", "Pack de 3 pares", "Reebok", "Moda y Accesorios", "M017", "img/moda y accesorios/M017.jpg", 200.0},
        {"Reloj digital", "Reloj resistente al agua", "Timex", "Moda y Accesorios", "M018",  "img/moda y accesorios/M018.jpg",1200.0},
        {"Mochila urbana", "Mochila para laptop", "Totto", "Moda y Accesorios", "M019",  "img/moda y accesorios/M019.jpg",950.0},
        {"Bufanda de lana", "Bufanda para invierno", "Springfield", "Moda y Accesorios", "M020",  "img/moda y accesorios/M020.jpg",400.0},

        // Deportes y Aire Libre (20)
        {"Balón de fútbol", "Balón profesional talla 5", "Adidas", "Deportes y Aire Libre", "D001", "img/deportes y aire libre/D001.jpg", 600.0},
        {"Balón de baloncesto", "Balón oficial", "Spalding", "Deportes y Aire Libre", "D002", "img/deportes y aire libre/D002.jpg", 700.0},
        {"Mancuernas 5kg", "Par de mancuernas", "Everlast", "Deportes y Aire Libre", "D003",  "img/deportes y aire libre/D003.jpg",800.0},
        {"Bicicleta de montaña", "Bicicleta con suspensión", "Benotto", "Deportes y Aire Libre", "D004", "img/deportes y aire libre/D004.jpg", 6500.0},
        {"Tienda de campaña 4p", "Tienda para 4 personas", "Ozark Trail", "Deportes y Aire Libre", "D005", "img/deportes y aire libre/D005.jpg", 3200.0},
        {"Ropa deportiva", "Conjunto deportivo", "Under Armour", "Deportes y Aire Libre", "D006", "img/deportes y aire libre/D006.jpg", 1200.0},
        {"Botella de agua reutilizable", "Botella de acero inoxidable", "CamelBak", "Deportes y Aire Libre", "D007", "img/deportes y aire libre/D007.jpg", 350.0},
        {"Cuerda para saltar", "Cuerda ajustable", "Nike", "Deportes y Aire Libre", "D008", "img/deportes y aire libre/D008.jpg",180.0},
        {"Colchoneta de yoga", "Tapete antideslizante", "Gaiam", "Deportes y Aire Libre", "D009", "img/deportes y aire libre/D009.jpg", 400.0},
        {"Raqueta de tenis", "Raqueta ligera", "Wilson", "Deportes y Aire Libre", "D010",  "img/deportes y aire libre/D010.jpg",1500.0},
        {"Guantes de gimnasio", "Guantes antideslizantes", "Adidas", "Deportes y Aire Libre", "D011", "img/deportes y aire libre/D011.jpg", 300.0},
        {"Casco para ciclismo", "Casco ajustable", "Specialized", "Deportes y Aire Libre", "D012", "img/deportes y aire libre/D012.jpg", 900.0},
        {"Patines en línea", "Patines para adultos", "Rollerblade", "Deportes y Aire Libre", "D013", "img/deportes y aire libre/D013.jpg", 2200.0},
        {"Saco de dormir", "Saco térmico", "Coleman", "Deportes y Aire Libre", "D014", "img/deportes y aire libre/D014.jpg", 950.0},
        {"Lámpara de camping", "Lámpara LED recargable", "Energizer", "Deportes y Aire Libre", "D015", "img/deportes y aire libre/D015.jpg", 400.0},
        {"Bastones de trekking", "Par de bastones", "Black Diamond", "Deportes y Aire Libre", "D016", "img/deportes y aire libre/D016.jpg", 1100.0},
        {"Chaleco salvavidas", "Chaleco para deportes acuáticos", "Speedo", "Deportes y Aire Libre", "D017",  "img/deportes y aire libre/D017.jpg",850.0},
        {"Gorra deportiva", "Gorra transpirable", "Nike", "Deportes y Aire Libre", "D018",  "img/deportes y aire libre/D018.jpg",250.0},
        {"Bicicleta urbana", "Bicicleta ligera para ciudad", "Mercurio", "Deportes y Aire Libre", "D019", "img/deportes y aire libre/D019.jpg", 5200.0},
        {"Bolsa de deporte", "Bolsa grande para gimnasio", "Puma", "Deportes y Aire Libre", "D020", "img/deportes y aire libre/D020.jpg", 700.0},

        // Cuidado personal y belleza (20)
        {"Crema hidratante facial", "Crema para piel seca", "Nivea", "Cuidado personal y belleza", "B001", "img/cuidado personal y belleza/B001.jpg", 180.0},
        {"Perfume floral", "Fragancia para dama", "Carolina Herrera", "Cuidado personal y belleza", "B002", "img/cuidado personal y belleza/B002.jpg", 2100.0},
        {"Champú anticaspa", "Champú para uso diario", "Head & Shoulders", "Cuidado personal y belleza", "B003", "img/cuidado personal y belleza/B003.jpg", 120.0},
        {"Maquillaje compacto", "Polvo compacto mate", "Maybelline", "Cuidado personal y belleza", "B004", "img/cuidado personal y belleza/B004.jpeg", 250.0},
        {"Cepillo de dientes eléctrico", "Cepillo recargable", "Oral-B", "Cuidado personal y belleza", "B005",  "img/cuidado personal y belleza/B005.jpg",600.0},
        {"Secador de pelo", "Secador profesional", "Remington", "Cuidado personal y belleza", "B006",  "img/cuidado personal y belleza/B006.jpg",950.0},
        {"Plancha para cabello", "Plancha de cerámica", "Babyliss", "Cuidado personal y belleza", "B007",  "img/cuidado personal y belleza/B007.jpg",1100.0},
        {"Crema antiarrugas", "Crema rejuvenecedora", "L'Oréal", "Cuidado personal y belleza", "B008",  "img/cuidado personal y belleza/B008.jpg",350.0},
        {"Desodorante roll-on", "Desodorante sin alcohol", "Rexona", "Cuidado personal y belleza", "B009", "img/cuidado personal y belleza/B009.jpg", 70.0},
        {"Gel de baño", "Gel hidratante para ducha", "Palmolive", "Cuidado personal y belleza", "B010", "img/cuidado personal y belleza/B010.jpg", 90.0},
        {"Afeitadora eléctrica", "Afeitadora recargable", "Philips", "Cuidado personal y belleza", "B011",  "img/cuidado personal y belleza/B011.jpg",1300.0},
        {"Esmalte de uñas", "Esmalte de larga duración", "Sally Hansen", "Cuidado personal y belleza", "B012", "img/cuidado personal y belleza/B012.jpg", 120.0},
        {"Loción corporal", "Loción hidratante", "Vaseline", "Cuidado personal y belleza", "B013", "img/cuidado personal y belleza/B013.jpg", 150.0},
        {"Mascarilla facial", "Mascarilla purificante", "Garnier", "Cuidado personal y belleza", "B014", "img/cuidado personal y belleza/B014.jpg", 80.0},
        {"Crema para manos", "Crema nutritiva", "Neutrogena", "Cuidado personal y belleza", "B015", "img/cuidado personal y belleza/B015.jpg", 90.0},
        {"Protector solar SPF50", "Protección solar alta", "Banana Boat", "Cuidado personal y belleza", "B016", "img/cuidado personal y belleza/B016.jpg", 220.0},
        {"Tijeras para uñas", "Tijeras de acero inoxidable", "Revlon", "Cuidado personal y belleza", "B017", "img/cuidado personal y belleza/B017.jpg", 60.0},
        {"Cepillo para cabello", "Cepillo desenredante", "Conair", "Cuidado personal y belleza", "B018", "img/cuidado personal y belleza/B018.jpg", 130.0},
        {"Crema depilatoria", "Crema para piel sensible", "Veet", "Cuidado personal y belleza", "B019", "img/cuidado personal y belleza/B019.jpg", 100.0},
        {"Kit de maquillaje", "Set completo de maquillaje", "MAC", "Cuidado personal y belleza", "B020", "img/cuidado personal y belleza/B020.jpg", 1800.0}
    };
}

#endif // LISTA_PRODUCTOS_H